### ISSUE TITLE
two more bad referrers need to be added on the list

### ISSUE THREAD

**Issue by elaur** [mariusv/nginx-badbot-blocker#10]
Last month my page got some search from this two websites ghostvisitor.com and ilovevitality.xyz who is generating fake trafic.
![img](https://s3.amazonaws.com/f.cl.ly/items/0V0j3E3i1K2L18423w3y/Image%202016-07-15%20at%203.33.09%20pm.png)

**Comment by mitchellkrogza** [comment]
Just updated my globalblacklist.conf. Thanks for the info on the new baddies.

**Comment by mariusv** [comment]
Thanks @mitchellkrogza for the quick response and @elaur for the report.
Will close the issue as was fixed with 36eacfb commit 👍
