### ISSUE TITLE
IP blocks not reliable anymore with providers using CGNAT

### ISSUE THREAD

**Issue by n3storm** [mariusv/nginx-badbot-blocker#114]
I have several customers that cannot connect to server. After investigation their provider is MasMovil (Spain) that is implementing CGNAT in all their network. Some other Spanish providers are planning to implement this too.

Affected blockips.conf ranges are:

```
deny 139.47.0.0/16;
deny 139.167.0.0/16;
deny 139.188.0.0/16;
```

But others cannot be trusted as "bad guys" anymore IMHO and I am disabling blockips.conf completelly.

**Comment by n3storm** [comment]
Edited for clarity

**Comment by mitchellkrogza** [comment]
With my mainstream version of the blocker you can customize the IP blocking as you like.
Why drop use of the entire blocker which protects you against thousands of bad referers?
