### ISSUE TITLE
Map Directive. 

### ISSUE THREAD

**Issue by Az0nic** [mariusv/nginx-badbot-blocker#117]
After following the configuration instructions, whilst running: sudo nginx -t to confirm everything is correct I received this error message: 

nginx: [emerg] "map" directive is not allowed here in /etc/nginx/conf.d/blacklist.conf:129
nginx: configuration file /etc/nginx/nginx.conf test failed

Any reason why? =)

**Comment by mitchellkrogza** [comment]
Please post output of 'sudo nginx -v' possible your Nginx does not have all
required extras. Also What Linux distribution are you on?

**Comment by mitchellkrogza** [comment]
Sorry 'sudo nginx-V'

**Comment by Evoley** [comment]
I seem to have the same problem. The offending line for me is 

> map $http_user_agent $bad_bot {

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

nginx -v
nginx version: nginx/1.12.1

**Comment by mitchellkrogza** [comment]
Please post your nginx.conf and vhost.conf here. Also did you install Nginx with sudo apt install -y nginx nginx-extras???  You maybe don't have the map module installed but I do also need to see where you have done your includes in Nginx.conf and your vhost.conf please

**Comment by Evoley** [comment]
I installed nginx from the [ppa](https://launchpad.net/~nginx/+archive/ubuntu/stable)

nginx.conf
> user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 1024;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;
	variables_hash_max_size 2048;
	server_names_hash_max_size 4096;
        server_names_hash_bucket_size 64;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;
		

	limit_conn_zone $binary_remote_addr zone=server3:10m;
	limit_conn_zone $server_name zone=server2:10m;


        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##
        gzip on;
        gzip_disable "msie6";

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

         include /etc/nginx/sites-enabled/*;
	include /etc/nginx/hosts.d/*.conf;
	
		
		server {
#                include hosts.d/*.conf;


I don't have a vhost.conf but here's the server block that i'm using for a domain

> server {
                listen 48158 default; #IPv4
                #listen [::]:35489 default; #IPv6
                autoindex on; #this is the file list
		index  index.html  index.php;
		ssl on;
		ssl_certificate /etc/letsencrypt/live/serverssl/fullchain.pem;
        	ssl_certificate_key /etc/letsencrypt/live/serverssl/privkey.pem;
		server_name server2;

                # path you want to share
                root /directory/im/sharing

		limit_conn server3 5;
		limit_conn server2 10;

**Comment by mitchellkrogza** [comment]
@Evoley you are missing `include /etc/nginx/conf.d/*.conf;` in your nginx.conf file. also you have not posted your complete vhost.conf and what you did post shows NO includes for the bot blocker.

**Comment by Evoley** [comment]
Like I said I don't have a vhost.conf file. I never got one when I installed nginx and the reason why I don't have include /etc/nginx/conf.d/*.conf; is because of nginx: [emerg] "map" directive is not allowed here in /etc/nginx/conf.d/blacklist.conf:129

**Comment by mitchellkrogza** [comment]
@Evoley your vhost.conf needs this includes like this

```
server {
                listen 48158 default; #IPv4
                #listen [::]:35489 default; #IPv6
                autoindex on; #this is the file list
		index  index.html  index.php;

                #Bot Blocker
                include /etc/nginx/bots.d/blockbots.conf;
                include /etc/nginx/bots.d/ddos.conf;
		ssl on;
		ssl_certificate /etc/letsencrypt/live/serverssl/fullchain.pem;
        	ssl_certificate_key /etc/letsencrypt/live/serverssl/privkey.pem;
		server_name server2;

                # path you want to share
                root /directory/im/sharing

		limit_conn server3 5;
		limit_conn server2 10;

		
```

**Comment by mitchellkrogza** [comment]
@Evoley please post output again of `sudo nginx -V` it should look like this

```
nginx -V
nginx version: nginx/1.10.3 (Ubuntu)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_perl_module --with-http_random_index_module --with-http_secure_link_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module --with-threads --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/headers-more-nginx-module --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/nginx-auth-pam --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/nginx-cache-purge --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/nginx-dav-ext-module --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/nginx-development-kit --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/nginx-echo --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/ngx-fancyindex --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/nginx-http-push --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/nginx-lua --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/nginx-upload-progress --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/nginx-upstream-fair --add-module=/build/nginx-Q158zN/nginx-1.10.3/debian/modules/ngx_http_substitutions_filter_module
```

**Comment by mitchellkrogza** [comment]
Also what version of the blocker are you using ?? VERSION_2 ??

**Comment by Evoley** [comment]
Hostname:~# nginx -v
nginx version: nginx/1.12.1
Hostname:~#
Yeah i'm using v2.

**Comment by mitchellkrogza** [comment]
@Evoley as mentioned earlier you are missing `include /etc/nginx/conf.d/*.conf;` in your nginx.conf file. 

You also need to put the includes in your server {} block as follows.

```
server {
                listen 48158 default; #IPv4
                #listen [::]:35489 default; #IPv6
                autoindex on; #this is the file list
		index  index.html  index.php;

                #Bot Blocker
                include /etc/nginx/bots.d/blockbots.conf;
                include /etc/nginx/bots.d/ddos.conf;

		ssl on;
		ssl_certificate /etc/letsencrypt/live/serverssl/fullchain.pem;
        	ssl_certificate_key /etc/letsencrypt/live/serverssl/privkey.pem;
		server_name server2;

                # path you want to share
                root /directory/im/sharing

		limit_conn server3 5;
		limit_conn server2 10;
```
