### ISSUE TITLE
[v2 errors] - Latest version errors in nginx 1.13.3

### ISSUE THREAD

**Issue by bramswenson** [mariusv/nginx-badbot-blocker#132]
```
nginx: [emerg] invalid number of the geo parameters in /etc/nginx/conf.d/blacklist.conf:6224     
```

**Comment by bramswenson** [comment]
I pull the file directly from github on build like so:
```
curl -sL https://github.com/mariusv/nginx-badbot-blocker/raw/master/VERSION_2/conf.d/blacklist.conf \
     -o /etc/nginx/conf.d/blacklist.conf \
  && curl -sL https://github.com/mariusv/nginx-badbot-blocker/raw/master/VERSION_2/bots.d/blockbots.conf \
          -o /etc/nginx/bots.d/blockbots.conf \
  && curl -sL https://github.com/mariusv/nginx-badbot-blocker/raw/master/VERSION_2/bots.d/ddos.conf \
          -o /etc/nginx/bots.d/ddos.conf
```

**Comment by mitchellkrogza** [comment]
Please Post your vhost config file, have hundreds of people using this
without problems possible you have done your include in the wrong place.

**Comment by mitchellkrogza** [comment]
Why do you not pull the raw files as per the instructions using wget?

**Comment by mitchellkrogza** [comment]
Why are you pulling the files using curl and not wget as per the
instructions????

**Comment by bramswenson** [comment]
My base image does not have wget and I don't want to install it. This isn't the issue. I've been using v2 for a while without issue. A specific commit broke things for me. The breaking commit is `c81a99ca75d5c4266df826800d78bf12b5209d95`. Here is a summary of my build results, any commit in `Breaks:` bombs with the error I pasted initially:
```
Broken:                                                                                                                                                                
NGINX_BADBOT_BLOCKER_VERSION=4803f167d41213fa6aaa232c5697a2268e7000a2
NGINX_BADBOT_BLOCKER_VERSION=cf064f4717d65723bb611d22cea1e535f21e0447
NGINX_BADBOT_BLOCKER_VERSION=c81a99ca75d5c4266df826800d78bf12b5209d95
Works:
NGINX_BADBOT_BLOCKER_VERSION=4a25c6d52754e20e6fa66399491c32f86be91c3c
NGINX_BADBOT_BLOCKER_VERSION=de1f717e8b123f950e8515ccfb3787a5e945feef
```

**Comment by bramswenson** [comment]
Isn't the structure of these map entries malformed? I don't know nearly what you do on the subject, but I suspect they are:
https://github.com/mariusv/nginx-badbot-blocker/blob/c81a99ca75d5c4266df826800d78bf12b5209d95/VERSION_2/conf.d/blacklist.conf#L6102-L6199

**Comment by bramswenson** [comment]
Yes, in fact that is 100% the issue @mitchellkrogza not my use of `curl` over `wget`. Whatever/whoever is creating the `blacklist.conf` is errored. :sunglasses:

**Comment by mitchellkrogza** [comment]
@bramswenson my apologies, some recent scripting changes in the generator caused the ip blocks in `geo $validate_client {` to be written as:

```
# START CYVEILLANCE BLOCK ### DO NOT EDIT THIS LINE AT ALL ###
	38.100.19.8/29		
	38.100.21.0/24		
	38.100.41.64/26		
	38.105.71.0/25		
	38.105.83.0/27		
	38.112.21.140/30		
	38.118.42.32/29		
	63.144.0.0/13		
	65.112.0.0/12		
	65.213.208.128/27		
	65.222.176.96/27		
	65.222.185.72/29		
# END CYVEILLANCE BLOCK ### DO NOT EDIT THIS LINE AT ALL ###
```
instead of

```
# START CYVEILLANCE BLOCK ### DO NOT EDIT THIS LINE AT ALL ###
	38.100.19.8/29		0;
	38.100.21.0/24		0;
	38.100.41.64/26		0;
	38.105.71.0/25		0;
	38.105.83.0/27		0;
	38.112.21.140/30		0;
	38.118.42.32/29		0;
	63.144.0.0/13		0;
	65.112.0.0/12		0;
	65.213.208.128/27		0;
	65.222.176.96/27		0;
	65.222.185.72/29		0;
# END CYVEILLANCE BLOCK ### DO NOT EDIT THIS LINE AT ALL ###
```

Fixed in https://github.com/mariusv/nginx-badbot-blocker/pull/133

**Comment by mitchellkrogza** [comment]
@bramswenson  I will also add your curl options to the Readme / Instructions for those like you do not have wget. Apologies for the outage caused and the horrible EMERG errors.

**Comment by bramswenson** [comment]
@mitchellkrogza No worries buddy, Thanks for fixing it and thanks for maintaining such a useful project.

**Comment by mitchellkrogza** [comment]
No problem at all and glad I could fix it quick, before other people's servers started EMERG'ing. Enjoy and so glad to hear you find the blocker so useful.
