### ISSUE TITLE
URL with ambiente returns 444

### ISSUE THREAD

**Issue by slideup-benni** [mariusv/nginx-badbot-blocker#137]
Hello,

i have a similar problem to #127.

A page with a url-part "ambiente" doesn't load any content like css, images, js because of the badword:
        "~*ambien"              1;
eg. www.example.com/ambiente.

I added the domain to whitelist-domains.conf, but it doesn't work.
My understanding is, that when i whitelist a domain, it shouldn't check for badwords, because it is on a whitelisted domain. Is this correct?

**Comment by mitchellkrogza** [comment]
@slideup-benni latest version has removed the bad-referrer-word scanning section as it led to false positives. Please download latest version of blacklist.conf from `https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/VERSION_2/conf.d/blacklist.conf` L731 > L739 no longer does any checking for bad referrer words.
