### ISSUE TITLE
YandexBot

### ISSUE THREAD

**Issue by extensionsapp** [mariusv/nginx-badbot-blocker#141]
Hello.

Maybe YandexBot is good bot?

**Comment by mitchellkrogza** [comment]
In **VERSION_2** YandexBot is not blocked, it is in the rate limited section so if it gets too greedy it will be slowed down on it's crawling. See line 203 of blacklist.conf.

`"~*\bYandexBot\b"		2;`

**Comment by extensionsapp** [comment]
@mitchellkrogza Can you tell me what restrictions are imposed on it?

**Comment by mitchellkrogza** [comment]
@extensionsapp the only limitations on YandexBot are rate limiting as per this rate limiting zone.

```
	limit_conn_zone $bot_iplimit zone=bot2_connlimit:16m;
	limit_req_zone  $bot_iplimit zone=bot2_reqlimitip:16m  rate=2r/s;
```

**Comment by mitchellkrogza** [comment]
Personally I run 28 sites off one server and Yandex has never ever been rate limited so I think in next update I might just move it into the "Allowed Bots" section. Yandex used to get out of hand on some people's sites but it seems they have cleaned up their act and also taught their crawler to behave.

**Comment by extensionsapp** [comment]
Excellent. Now I find out from Yandex's support what will happen if I limit up to 2 requests per second. Will the site be downgraded in search results or not.

**Comment by extensionsapp** [comment]
I think it makes sense in robots.txt to tell him about the constraint.

<img width="566" alt="screenshot_12" src="https://user-images.githubusercontent.com/8192379/31023067-671d4140-a543-11e7-9635-eb5ce0022b73.png">

But it is better to remove the restriction altogether.

**Comment by mitchellkrogza** [comment]
If you grep your web site error.log(s) for Yandex and get nothing then you know immediately you have never ever rate limited them. Rate Limiting won't do anything to your rankings, it just slows their crawler down and it will come back later and carry on elsewhere but I DO think it can move to Allowed Bots.

**Comment by mitchellkrogza** [comment]
@extensionsapp will address in next update
