### ISSUE TITLE
Jorgee Vulnerability Scanner

### ISSUE THREAD

**Issue by FNCxPro** [mariusv/nginx-badbot-blocker#163]
Request for the `Mozilla/5.0 Jorgee` useragent to be blocked  

![Image of Jorgee scanner scanning website](https://discord-banned.me/3HBrXg.png)

**Comment by mitchellkrogza** [comment]
@FNCxPro it was added in a prior commit see https://github.com/mariusv/nginx-badbot-blocker/blob/master/VERSION_2/conf.d/blacklist.conf#L429 please confirm you have the latest update.

**Comment by FNCxPro** [comment]
Sorry, when i `ctrl` + `f`'d for `Jorgee` I spelt it wrong. Thanks
