### ISSUE TITLE
Whitelist IPs add IPs CloudFlare

### ISSUE THREAD

**Issue by botaniQQQ** [mariusv/nginx-badbot-blocker#168]
I noticed that the IP CloudFlare began to get blocked and, accordingly, the site traffic decreased. I think adding this IP list would be a very good solution.

https://github.com/mariusv/nginx-badbot-blocker/blob/master/VERSION_2/bots.d/whitelist-ips.conf
https://www.cloudflare.com/ips/

```
# Add One Entry Per Line - Can Include Ranges like 127.0.0.1/32
127.0.0.1		0;
103.21.244.0/22		0;
103.22.200.0/22		0;
103.31.4.0/22		0;
104.16.0.0/12		0;
108.162.192.0/18		0;
131.0.72.0/22		0;
141.101.64.0/18		0;
162.158.0.0/15		0;
172.64.0.0/13		0;
173.245.48.0/20		0;
188.114.96.0/20		0;
190.93.240.0/20		0;
197.234.240.0/22		0;
198.41.128.0/17		0;
```

**Comment by mariusv** [comment]
Heya @botaniQQQ ,

I just had a look at the `blockips.conf` and none of the CloudFlare IPs are in there. The way how it works is that if an IP is not in `blockips.conf` then is whitelisted by default. Do you have any logs where nginx is blocking CloudFlare IPs?

Thanks a lot for the report.
