### ISSUE TITLE
IP blocks

### ISSUE THREAD

**Issue by seansan** [mariusv/nginx-badbot-blocker#17]
Is it smarter to block these IP's in nginx? or smarter to put them in our firewal black list? 

Interested in understanding what is faster / cq better

**Comment by mitchellkrogza** [comment]
Known BAD IPS …. block them in iptables and be done with them. Better yet use Fail2Ban to do it for you.


On 12 August 2016 at 1:45:26 PM, seansan (notifications@github.com) wrote:

Is it smarter to block these IP's in nginx? or smarter to put them in our firewal black list?

Interested in understanding what is faster / cq better

**Comment by seansan** [comment]
So would you suggest adding badips to firewall, insteaf of using the nginx
conf file in this github?

**Comment by mitchellkrogza** [comment]
Nginx just handles them fine with a nice 444 drop connection error. I had one web site hot linking an image from my photography site 4 days ago that I picked up so I added them to the bad referers, they picked up the 444 error in their logs and they got rather angry and flooded that site with over 39000 connections in one hour. Nginx immediately rate limited them big time but they did not stop … so for that one I just added them to my Fail2Ban perma-ban blacklist and that’s it they are banned permanently and also blacklisted on badips.com. 

Nginx however just utterly laughed at the 39000+ connections, it had not effect on any operations or any other web sites. Had it been Apache the server would have crashed or stopped being able to serve any more web sites.

Will keep you updated when my new version is released.


On 12 August 2016 at 3:43:21 PM, seansan (notifications@github.com) wrote:

So would you suggest adding badips to firewall, insteaf of using the nginx
conf file in this github?

**Comment by mariusv** [comment]
I will close this as the question has been answered If you feel like you didn't got the answer please feel free to re-open it.

Thank you!
