### ISSUE TITLE
Change user agent for OpenVAS

### ISSUE THREAD

**Issue by groggu** [mariusv/nginx-badbot-blocker#175]
Open Vulnerability Assessment System has changed it user agent.  Change Openvas to OpenVAS to match.  

Examples -
"Mozilla/5.0 [en] (X11, U; OpenVAS 7.0.10)"
"Mozilla/5.0 [en] (X11, U; OpenVAS 8.0.9)"
{ OpenVAS:; };
{ _; OpenVAS; }

**Comment by mitchellkrogza** [comment]
Will be addressed tomorrow including a long overdue update.
