### ISSUE TITLE
incorrect block

### ISSUE THREAD

**Issue by seansan** [mariusv/nginx-badbot-blocker#18]
https://domain.com/adyen/process/ins

a POST is made on 443 SSL

this URL is blocked we have no idea why .... (payment provider is being blocked)

**Comment by mariusv** [comment]
Can you please show the request as you see it in the logs?

**Comment by seansan** [comment]
./access.log:82.199.90.162 - adyen [13/Aug/2016:10:46:53 +0200] "POST /adyen/process/ins HTTP/1.1" 200 41 "-" "Apache-HttpClient/4.4.1 (Java/1.8.0_92)"

**Comment by mariusv** [comment]
Renove this two entries `^Java|Java` from `map $http_user_agent $bad_bot {` block and you should be good to go.

**Comment by seansan** [comment]
Is this because of the open Java match? I see both ^Java and Java in the bot list: Java is maybe a little too wide?

**Comment by mariusv** [comment]
It is indeed, I will look at a way to make that part better.
Thank you for reporting it.

**Comment by mitchellkrogza** [comment]
That was one of the false positives I mentioned in my email yesterday. There are some good bots using Java in their user agent string and this match was indeed too wide. My new version of the blocker deals with user agents much more explicitly and not wildcarded. There is another one too ^NG which picks up bits named Bing. Check that one out too.

**Comment by mitchellkrogza** [comment]
We should remove ^Java|Java permanently from the blacklist.conf file.
I've seen a number of very legitimate google clients using Java in their user agent string. Must I send a PR and take them out?

**Comment by mitchellkrogza** [comment]
Removed in https://github.com/mariusv/nginx-badbot-blocker/pull/32
with examples of why it should not be there

**Comment by mitchellkrogza** [comment]
Has been removed now with latest merge https://github.com/mariusv/nginx-badbot-blocker/commit/88eb800963a0c1ba8a72916241eeab94b5803799
