### ISSUE TITLE
Nginx server error

### ISSUE THREAD

**Issue by beeriz** [mariusv/nginx-badbot-blocker#180]
Hi. 

_I'm getting this error after updating the filters: 

nginx: [emerg] limit_conn_zone "bot2_connlimit" is already bound to key "$bot_iplimit" in /etc/nginx/conf.d/blacklist.conf:7614
nginx: configuration file /etc/nginx/nginx.conf test failed
I have to comment : 
	# limit_conn_zone $bot_iplimit zone=bot2_connlimit:16m;
	# limit_req_zone  $bot_iplimit zone=bot2_reqlimitip:16m  rate=2r/s;

to be able to reboot the nginx server.
Any idea what's happening?_

Resolved 👍 
I have changed my blacklist.conf location and then when updated it created a double.
Thanks

**Comment by mariusv** [comment]
Thanks for reporting it back that this was solved. I'll close the issue now.
