### ISSUE TITLE
TESTING question

### ISSUE THREAD

**Issue by bobrovalex** [mariusv/nginx-badbot-blocker#191]
I am testing with http in command line
`curl -A "80legs" http://mydomain`
responce is:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
 http**S** in command line
`curl -A "80legs" https://mydomain`
responce is:
`curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)`

is this a problem ?

**Comment by mitchellkrogza** [comment]
`curl: (92) HTTP/2 stream 1 was not closed cleanly:` means the blocker is working. SSL sites return this different error.

**Comment by bobrovalex** [comment]
thanks
