### ISSUE TITLE
Bad bot suggestion

### ISSUE THREAD

**Issue by Yinchie** [mariusv/nginx-badbot-blocker#20]
Recently saw the following in my logs.
"WebFuck V2.1 T0PHackTeam www.t0p.xyz"

Perhaps adding WebFuck into the bad bot section?

**Comment by mariusv** [comment]
Heya @Yinchie ,

Thanks for the report..added the new bot to the list with commit 221bddc . For the future you can always do a pull request as will make things faster :-)
Thank you!
