### ISSUE TITLE
Does nginx still log bot access after implementing?

### ISSUE THREAD

**Issue by mogsama** [mariusv/nginx-badbot-blocker#23]
Hi,

After adding the code and file, I still see blocked bots name in nginx's access log. So I'm wondering whether I'm doing it right or not. How do I know the block policies are working?

For example:
180.76.15.20 0.012 - [29/Dec/2016:02:30:55 +0000] abc.com "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"

163.172.66.3 0.210 - [29/Dec/2016:04:15:22 +0000] abc.com "GET /en/other HTTP/1.1" 200 15251 "-" "Mozilla/5.0 (compatible; AhrefsBot/5.2; +http://ahrefs.com/robot/)"

**Comment by mitchellkrogza** [comment]
I have a Fail2Ban filter which monitors the logs for "444" or "403" errors and then block the big abusers at IPtables level which stops them filling your logs. PM me if you want the Fail2Ban filter. I'll send a PR here to include it in this repo.

**Comment by UiharuKazari2008** [comment]
@mitchellkrogza Can i get that filter? I also want to setup something similar to IP ban someone that requests a "trip page". How do i PM on GitHub?

**Comment by mitchellkrogza** [comment]
I've sent it in with my latest PR.
https://github.com/mariusv/nginx-badbot-blocker/pull/32

**Comment by mitchellkrogza** [comment]
Fail2Ban filter added with latest merge https://github.com/mariusv/nginx-badbot-blocker/commit/88eb800963a0c1ba8a72916241eeab94b5803799
