### ISSUE TITLE
http://testp3.pospr.waw.pl/testproxy.php Bot? 

### ISSUE THREAD

**Issue by rlam3** [mariusv/nginx-badbot-blocker#29]
I've been getting requests from this address on my server... 

http://testp3.pospr.waw.pl/testproxy.php

Was wondering if this was included in the file too. 

Thanks!

**Comment by mitchellkrogza** [comment]
Checked it out and added it to latest PR https://github.com/mariusv/nginx-badbot-blocker/pull/32

**Comment by mitchellkrogza** [comment]
Added with latest merge https://github.com/mariusv/nginx-badbot-blocker/commit/88eb800963a0c1ba8a72916241eeab94b5803799
