### ISSUE TITLE
Too long parameter

### ISSUE THREAD

**Issue by Yinchie** [mariusv/nginx-badbot-blocker#31]
`nginx: [emerg] too long parameter "~(?i)(^htt..." started in /etc/nginx/includes/blacklist.conf:88`

**Comment by mitchellkrogza** [comment]
Busy looking into this, hang fire.

**Comment by mitchellkrogza** [comment]
Have split new domains added yesterday into two new sections bad_urls5 and bad_urls6. Have tested latest PR https://github.com/mariusv/nginx-badbot-blocker/pull/32 and no EMERG errors of any sort from Nginx. Wait for @mariusv  to merge and try with new one.

Make sure you also have:
	server_names_hash_bucket_size 64;
	server_names_hash_max_size 4096;

In your nginx.conf file to allow loading a file like this with lots of domains that need to be loaded into memory by Nginx.

**Comment by mariusv** [comment]
Merge completed.

**Comment by mitchellkrogza** [comment]
Cool stuff Marius 😉
