### ISSUE TITLE
Suggestion: json and makefile

### ISSUE THREAD

**Issue by n3storm** [mariusv/nginx-badbot-blocker#33]
I suggest to evaluate moving badbots list to a json file/s (including sections) and adding a makefile that will concatenate json list in a file for nginx comsumption.

- Helps list maintenance (diff, sorting, ...)
- Adding custom sections by using multiple json files.
- Implementation with avoiding duplicates.

YAML or any other human readable format should be fine too.

**Comment by mitchellkrogza** [comment]
I am actually busy on just such a system

**Comment by mariusv** [comment]
Heya @n3storm,

That is actually a great idea, please feel free to do a pull request with it and will be more than happy to accept it.

**Comment by mitchellkrogza** [comment]
Let's see if @n3storm beats me to it 😄

**Comment by n3storm** [comment]
Ow, too much of a burden, do not expect this this week. :)

**Comment by n3storm** [comment]
@mitchellkrogza if you wan't me to test I have some small systems to break.

I could be faster than you in python though.

**Comment by mitchellkrogza** [comment]
I already have a nice json composer script in progress (almost perfect) which can do the job perfectly. Just need to finish it up and apply it to this project. Will probably happen within the next 2-3 days. Once I push it out I think I will put it in a "version 2" folder of it's own until @mariusv and yourself can test

**Comment by mitchellkrogza** [comment]
Almost done on this, hopefully tomorrow or Saturday morning I will push out the new version.

**Comment by mitchellkrogza** [comment]
Version 2 pushed out this morning. Looking forward to your feedback before we can archive version 1 and move Version 2 into the root. Generator scripts coming shortly.
