### ISSUE TITLE
need a slack support channel? and also sample block setup?

### ISSUE THREAD

**Issue by rlam3** [mariusv/nginx-badbot-blocker#34]
need a slack support channel? 

was wondering if you could provide a sample block for setup?

thanks!

**Comment by rlam3** [comment]
also would it be correct if we moved these two files into the conf.d/ directory and include the conf.d/ directory be the same?

**Comment by mitchellkrogza** [comment]
You can put the files into a conf.d directory and do the include referencing that folder ... there should be no problem.

**Comment by mariusv** [comment]
@rlam3, I'm not sure a Slack channel is needed for this as the comunity around this config is relatively small and not sure will make sense...I would consider and look into having a slack channel if you want and there will be enough people requesting this.

thank you

**Comment by mitchellkrogza** [comment]
I think the current issue system is more than ample myself 👍

**Comment by mitchellkrogza** [comment]
Please look at new Version 2, very simple setup instructions.
