### ISSUE TITLE
please add 91.196.50.33

### ISSUE THREAD

**Issue by rlam3** [mariusv/nginx-badbot-blocker#35]
please add 91.196.50.33

**Comment by Yinchie** [comment]
A reason or a part of the log?

**Comment by rlam3** [comment]
its a bot from poland trying to access 404 links. 

Mainly it was trying to do the following: 

http://testp1.piwo.pila.pl/testproxy.php

**Comment by mariusv** [comment]
Heya @rlam3 ,

Would be great if you post the part of the log where this IP is crawling your website for 404s. So far this is only one IP which will definitely change with ease for the bot owner.

**Comment by mitchellkrogza** [comment]
Agree, bots change IP's too quickly. A log extract would be much more helpful.

**Comment by rlam3** [comment]
@mariusv 

logs for different ips again pinging the server.. 

```
2017/01/23 16:37:11 [error] 976#0: *199 access forbidden by rule, client: 185.49.14.190, server: midori.io, request: "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1", host: "testp3.pospr.waw.pl"
2017/01/24 04:32:52 [error] 15151#0: *280 access forbidden by rule, client: 185.49.14.190, server: midori.io, request: "GET http://testp1.piwo.pila.pl/testproxy.php HTTP/1.1", host: "testp1.piwo.pila.pl"
```

@mitchellkrogza what would it mean to block pile.pl at referer level? I'm a bit new to this. So would really appreciate if you could point me in the right direction. Thanks!

**Comment by mitchellkrogza** [comment]
I'll add pile.pl into a PR tomorrow. This will block them regardless of if they change IP address. We only add known bad IP's which are fixed and never changed. Big changes coming to this blocker in the next few days so keep a watch on this space.

**Comment by rlam3** [comment]
@mitchellkrogza thanks!

**Comment by mitchellkrogza** [comment]
Added in https://github.com/mariusv/nginx-badbot-blocker/pull/38/commits/0aac77dce2a34c2831f925cea955ebf1768c4ab6
