### ISSUE TITLE
Adding blockers

### ISSUE THREAD

**Issue by tomaadland** [mariusv/nginx-badbot-blocker#5]
Hi!

I came across this repo searching for a good solution to keep spam bots away. I still get a bunch of requests of the type: 
[GET] "/HNAP1"
[GET] "/dashboards"
[GET] "/login"

etc.. 

Some of these requests are registered as a Chrome, or FF or any other accepted browser out there. Was just wondering if you have any ideas on how to stop these if possible.

**Comment by charl** [comment]
Just blocking based on UA was not good enough for me so what I did was automatically generate a list of whitelisted routes for my app that I use as an access list via nginx to allow/block requests.

How you go about this is dependent on the tech used to build your app.

**Comment by tomaadland** [comment]
That's sort of what I thought as well. The app is a Rails application so the public routes before user has been authenticated is very limited. 

Thanks for your response.

**Comment by utags** [comment]
After I run "nginx -t" it gives following errors.
**nginx: [emerg] "geo" directive is not allowed here in /etc/nginx/common/blacklist.conf:22
nginx: [emerg] "map" directive is not allowed here in /etc/nginx/common/blacklist.conf:16**

Anyway to fix it?

**Comment by mariusv** [comment]
@utags , what nginx version you have? This is tested and works with nginx 1.10.0 (latest stable version) also where in `nginx.conf` have you added the `include blacklist.conf`?
Would be great if you cloud open another issue with this fro easier tracking.
Thank you

**Comment by mariusv** [comment]
@tomaadland looks like you need  [Naxsi ](https://github.com/nbs-system/naxsi), this will definitely solve your issue.

**Comment by mariusv** [comment]
Closing this issue.
