### ISSUE TITLE
Whitelist own IP's.

### ISSUE THREAD

**Issue by Yinchie** [mariusv/nginx-badbot-blocker#56]
According to the readme/instructions you have to manually add your own IP's at the bottom of the blacklist.

Isn't it easier to have a separate file for white listing?
Would make updating the blacklist file easier and smoother without the need to edit it every single time.

**Comment by mitchellkrogza** [comment]
I have completely sorted this issue out .... coming in tomorrow mornings PR. New method uses an include file system so no more having to remember to do it yourself. This means future daily updates require you to simply pull the globalblacklist.conf file and it will include your whitelists. Tomrrow morning promise, including updated configuration instructions.

**Comment by mitchellkrogza** [comment]
New include files method introduced in https://github.com/mariusv/nginx-badbot-blocker/commit/58f46d6bf7a0bd62353f5a99e6d626962ed5469d

Please read updated configuration instructions carefully regarding the include files if they are missing your nginx will give you an EMERG error. Super easy now to update without losing your whitelists 👍
