### ISSUE TITLE
Directive is not allowed here in issue.

### ISSUE THREAD

**Issue by utags** [mariusv/nginx-badbot-blocker#6]
I have Nginx 1.10.0 (Ubuntu 16.04, PHP-FPM5.6) VPS. I use **EasyEngine** to install Nginx, PHP, MySQL, etc stuff. After I added above configurations, when I run "nginx -t" it gives following errors.

**nginx: [emerg] "geo" directive is not allowed here in /etc/nginx/common/blacklist.conf:22
nginx: [emerg] "map" directive is not allowed here in /etc/nginx/common/blacklist.conf:16**

Nginx installed "**etc/nginx**". My additional configurations are placed inside the " **/etc/nginx/common/**" folder. In nginx directory "sites-available" sub-directory, I added following codes to each enabled Wordpress site config file.

>     include common/blacklist.conf;
>     include common/blockips.conf;

Anyway to fix it?

**Comment by mariusv** [comment]
@utags this values:

```
include common/blacklist.conf;
include common/blockips.conf;
```
have to be added in `/etc/nginx/nginx.conf` once you add them there the error will disappear .

**Comment by Yinchie** [comment]
Did you include the blacklist.conf and blockips.conf inside the "http" block? e.g. in the file /etc/nginx/nginx.conf

You should not include it into a "server" block.

**Comment by mariusv** [comment]
@utags , have you managed to make it work? Asking so I can close the issue.

Thank you

**Comment by utags** [comment]
Yes Mariusv. I have successfully added this block list to my Nginx configuration. One more question, how do I verify it's working properly?

**Comment by mariusv** [comment]
@utags , you can for example use curl to change the UserAgent to the ones blocked and see if they are blocked or not.
For Ex:
`curl -A "JikeSpider" http://url.com`
This will test if `JikeSpider` UserAgent is blocked.

**Comment by mariusv** [comment]
I will close this issue as it was solved. If you have anymore issue you can re-open it.
Thanks
