### ISSUE TITLE
Weird activity from 148.251.54.44

### ISSUE THREAD

**Issue by elaur** [mariusv/nginx-badbot-blocker#63]
Hi guys,

If anyone else have some tools to check/investigate this IP Adress 148.251.54.44 because is generating weird traffic on websites. What I found about it is just another complain here, http://whatismyipaddress.com/ip/148.251.54.44 and my activity log here https://cl.ly/3h1H1K0L3I3I and here https://cl.ly/1t2p3w3r2b1L, how you see is the only weird spike 31 hits from 22 visitors .

Thanks

**Comment by mitchellkrogza** [comment]
Just Grep'd through some logs on my servers. Lots of hits from this IP and always a different user agent string. 

Mozilla/5.0 (Windows NT 6.1; rv:6.0) Gecko/20100101 Firefox/19.0
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko Firefox/11.0
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.172 Safari/537.22
Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.16) Gecko/20120421 Gecko Firefox/11.0
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)
"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:21.0) Gecko/20130330 Firefox/21.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Safari/535.19

**Comment by elaur** [comment]
Same like me, someone else from http://whatismyipaddress.com/ip/148.251.54.44 got 601 hits in 59 secs from multiple user agents. A didn't find who own it mean some company to have a special purpose with it ... i don't know, copyright check bot, just someting but nothing. 3 resons why this IP adress should be banned.

**Comment by mitchellkrogza** [comment]
https://www.badips.com/info/148.251.54.44
http://anti-hacker-alliance.com/index.php?ip=148.251.54.44
http://botscout.com/ipcheck.htm?ip=148.251.54.44

**Comment by mitchellkrogza** [comment]
Added in https://github.com/mariusv/nginx-badbot-blocker/commit/2b3f4495830bdddba707c4c6d10a5f07a426c2ad
