### ISSUE TITLE
Some porn domain just found in my referring sites

### ISSUE THREAD

**Issue by elaur** [mariusv/nginx-badbot-blocker#64]
foto-sisek.porngalleries.top and maybe porngalleries.top

![](https://cl.ly/1E3y0F3E2H0O/Image%202017-02-22%20at%201.29.38%20pm.png)

**Comment by mitchellkrogza** [comment]
Will add in next release.

**Comment by mitchellkrogza** [comment]
Added in https://github.com/mariusv/nginx-badbot-blocker/commit/2b3f4495830bdddba707c4c6d10a5f07a426c2ad
