### ISSUE TITLE
sfFeedReader/0.9 should be added to User-Agent list with limits.

### ISSUE THREAD

**Issue by elaur** [mariusv/nginx-badbot-blocker#74]
I don't know I have seen some weird request from this user agent many times, and after some search I have discovered it is used mostly by web apps who is reading your rss feed. Anyway for me is a bit weird and I have placed it with "~*sfFeedReader/0.9"		2; in my list beacause my website is not so big and I know ai have maybe less than 10 people who is reading news via rss. For high volume website should be set with "1". All connections come from France / OVH / Kimsufi servers.

![log sfFeedReader/0.9](https://cl.ly/1r3X0w3U1w1M/Image%202017-02-25%20at%201.42.46%20am.png)

**Comment by mitchellkrogza** [comment]
Merged in https://github.com/mariusv/nginx-badbot-blocker/pull/75
