### ISSUE TITLE
Cron job to keep the list automatically updated

### ISSUE THREAD

**Issue by elaur** [mariusv/nginx-badbot-blocker#76]
Some cron job to keep the list automaticaly update.

First of all check to have wget installed.
> crontab -e
```
1 1 * * * /usr/bin/wget 'https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/VERSION_2/conf.d/blacklist.conf' -O /etc/nginx/conf.d/blacklist.conf
2 1 * * * /etc/init.d/nginx reload
```
> ctrl+x
> y

This cron job will download blacklist.conf automatically at 01:01AM and will reload nginx config at 01:02AM one minute later.

Good to be somewhere in readme, I don't want to update the list manual everytime, have other stuffs better to do, so let this cron job to do that for me.

**Comment by elaur** [comment]
It's unsafe

**Comment by mitchellkrogza** [comment]
Would be better to do it with a combination of a bash and cron to run the bash.

```
#!/bin/bash
cd /etc/nginx/conf.d
sudo wget https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/VERSION_2/conf.d/blacklist.conf -O blacklist.conf
sudo service nginx reload
mail -s "Bad Bot Blocker Updated" me@myemail.com
```
